name: Node.js CI

on:
    pull_request:
        branches:
            - '**'
    push:
        branches:
            - main

jobs:
    lint-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies, lint, and check
              run: |
                  npm ci
                  npm run lint
                  npm run check

            - name: Check exit code
              run: exit $?

    unit-tests:
        runs-on: ubuntu-latest
        needs: [lint-check]
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies and run unit tests
              run: |
                  npm ci
                  npm run test:unit

            - name: Check exit code
              run: exit $?

    publish-package:
        runs-on: ubuntu-latest
        needs: [unit-tests]
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Bump versions before publishing
              run: |
                  npm set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
                  npm version patch
                  npm ci
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}

            - name: Check exit code
              run: exit $?
